// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWz5gtTs67XjwQTn5gqozxCzJ9-mYluk',
    appId: '1:564023603906:web:5b60f6a231af2011fc415b',
    messagingSenderId: '564023603906',
    projectId: 'food-delivery-e0878',
    authDomain: 'food-delivery-e0878.firebaseapp.com',
    storageBucket: 'food-delivery-e0878.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAQMS357pd3Zu17R43R2vmOmQ_8XTuMQI',
    appId: '1:564023603906:android:d1a7b0866ad2263ffc415b',
    messagingSenderId: '564023603906',
    projectId: 'food-delivery-e0878',
    storageBucket: 'food-delivery-e0878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7kS-RChKa0anuHXxAVbBDlk2av4gbAc',
    appId: '1:564023603906:ios:1be32d331a359be9fc415b',
    messagingSenderId: '564023603906',
    projectId: 'food-delivery-e0878',
    storageBucket: 'food-delivery-e0878.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7kS-RChKa0anuHXxAVbBDlk2av4gbAc',
    appId: '1:564023603906:ios:1be32d331a359be9fc415b',
    messagingSenderId: '564023603906',
    projectId: 'food-delivery-e0878',
    storageBucket: 'food-delivery-e0878.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChWz5gtTs67XjwQTn5gqozxCzJ9-mYluk',
    appId: '1:564023603906:web:023570636a37700cfc415b',
    messagingSenderId: '564023603906',
    projectId: 'food-delivery-e0878',
    authDomain: 'food-delivery-e0878.firebaseapp.com',
    storageBucket: 'food-delivery-e0878.firebasestorage.app',
  );
}
